<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<?php echo $this->headScript(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->headTitle(); ?>

<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/default.css'); ?>

<!--[if IE]>
<link href="<?php $this->baseUrl(); ?>/css/ie.css" media="screen" rel="stylesheet" type="text/css" <?php echo (true === $this->xhtmlAllowed) ? '/' : ''; ?>>
<![endif]-->
<!--[if IE 6]>
<link href="<?php $this->baseUrl(); ?>/css/ie6.css" media="screen" rel="stylesheet" type="text/css" <?php echo (true === $this->xhtmlAllowed) ? '/' : ''; ?>>
<![endif]-->
<!--[if IE 7]>
<link href="<?php $this->baseUrl(); ?>/css/ie7.css" media="screen" rel="stylesheet" type="text/css" <?php echo (true === $this->xhtmlAllowed) ? '/' : ''; ?>>
<![endif]-->
<!--[if IE 8]>
<link href="<?php $this->baseUrl(); ?>/css/ie8.css" media="screen" rel="stylesheet" type="text/css" <?php echo (true === $this->xhtmlAllowed) ? '/' : ''; ?>>
<![endif]-->
<meta name="author" content="Richard Knop, risoknop@gmail.com" <?php echo (true === $this->xhtmlAllowed) ? '/' : ''; ?>>

</head>
<body>

<div id="wrapper">

    <div id="header">
        <h1><a href="/">Zend blank project v1.5</a></h1>
    </div>

<?php echo $this->layout()->content; ?>

    <div id="sidebar">
        <h2>Nunc a est elit</h2>
        <p>Nunc a est elit, a blandit lorem. Suspendisse sit amet arcu interdum nulla commodo dictum. Duis rutrum rutrum dolor eget varius.</p>
    </div>

    <div id="footer">
        <p>All contents copyright &copy; 2009 - PRESENT Your Name</p>
    </div>

</div>

<?php echo $this->inlineScript(); ?>


</body>
</html>